namespace RoadMusic.ClassLibrary.Database.Helpers
{
    /// <summary>
    /// Base class for database access.
    /// </summary>
	public abstract class DbClass
	{
        /// <summary>
        /// Message generated by a database operation.
        /// </summary>
		public string LastMessage { get; protected set; }
	}
}
